development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cvmaker_development
  pool: 5
  username: root
  password: "1234"	
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cvmaker_test
  pool: 5
  username: root
  password: "1234"	
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cvmaker_production
  pool: 5
  username: root
  password: "1234"
  socket: /var/run/mysqld/mysqld.sock
